GET http://tarefas.test/api/v1/tasklist/9
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vdGFyZWZhcy50ZXN0L2FwaS9sb2dpbiIsImlhdCI6MTYzNjMyNjM5OCwiZXhwIjoxNjM2MzI5OTk4LCJuYmYiOjE2MzYzMjYzOTgsImp0aSI6IlJTRzhockMydW1TRlZlc2wiLCJzdWIiOjIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.SiDfzyXqvoKGnIKWviPUEssNDe7aGlhAJw8tQW73oT0
